server:
  port: ${PORT}
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev,prod}
  application:
    name: SimpleToDoList
  security:
    user:
      name: ${SECURITY_USER_NAME}
      password: ${SECURITY_USER_PASSWORD}
      roles: ${SECURITY_USER_ROLES}
  jackson:
    date-format: ${DATE_TIME_FORMAT}
    time-zone: ${TIME_ZONE}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    out-of-order: false

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DATABASE_DEV_URL}
    username: ${DATABASE_DEV_USERNAME}
    password: ${DATABASE_DEV_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${JPA_HIBERNATE_DIALECT_DEV}
    show-sql: true
  flyway:
    locations: classpath:db/migration,classpath:db/dev

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_PROD_URL}
    username: ${DATABASE_PROD_USERNAME}
    password: ${DATABASE_PROD_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${JPA_HIBERNATE_DIALECT_PROD}
    show-sql: true
  flyway:
    locations: classpath:db/migration,classpath:db/test
    clean-disabled: false